#!/bin/bash

# Set this hostname
HOSTNAME=`hostname --short`

# Set Graphite host
GRAPHITE='192.168.0.114'
GRAPHITE_PORT=8125

# Loop forever
while :
do
	# Get epoch
	DATE=`date +%s`
	NEXTDATE=`expr $DATE + 10`
	CPU_USAGE=$(ps aux | awk {'sum+=$3;print sum/4'} | tail -n 1)
	#CPU_USAGE=$(mpstat | tail -1 | awk '{print 100-$12}')
	MEM_USAGE=$(ps aux | awk {'sum+=$4;print sum'} | tail -n 1)
	#MEM_USAGE=$(top -n 1 | grep Mem: | awk '{print $6/$4*100}')
	NODEJS_CPU=$(ps aux |grep cluster.js |awk {'sum+=$3; print sum'} |tail -n 1)
	NODEJS_MEM=$(ps aux |grep cluster.js |awk {'sum+=$4; print sum'} |tail -n 1)
	
	# Send data to Graphite
	# system cpu,memory
	# nodejs cpu,memory
	echo "${HOSTNAME}.system.cpu:${CPU_USAGE}|g
	${HOSTNAME}.system.mem:${MEM_USAGE}|g
	${HOSTNAME}.nodejs.cpu:${NODEJS_CPU}|g
	${HOSTNAME}.nodejs.mem:${NODEJS_MEM}|g" | nc -w 1 -u $GRAPHITE $GRAPHITE_PORT

	DATE=`date +%s`
	sleep `expr $NEXTDATE - $DATE`
done
